// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Bo Lin
//! End-to-end test for the `Perf.g4` recognizers in `tests/gen/`
//! (regenerated by `gen_test_grammars.sh`). `Perf.g4` stresses the
//! left-recursion machinery: prefix ops, a ternary `?:`, and
//! `between/and` in one recursive `expr` rule.

#[rustfmt::skip]
mod gen {
    // Generated parsers/lexers: lint with the codegen template, not here.
    #![allow(clippy::all, dead_code, unused, warnings)]
    pub mod perflexer;
    pub mod perflistener;
    pub mod perfparser;
}

use dbt_antlr_runtime::common_token_stream::CommonTokenStream;
use dbt_antlr_runtime::recognizer::Recognizer;
use dbt_antlr_runtime::token_factory::CommonTokenFactory;
use dbt_antlr_runtime::trees::string_tree;
use dbt_antlr_runtime::{Arena, InputStream};
use gen::perflexer::PerfLexer;
use gen::perfparser::PerfParser;

fn parse(input: &str) -> String {
    Arena::with(|arena| {
        let lexer = PerfLexer::<_, CommonTokenFactory>::new(arena, InputStream::new(input));
        let token_source = CommonTokenStream::new(lexer);
        let mut parser = PerfParser::new(arena, token_source);
        let result = parser.stat().expect("perf parse");
        string_tree(result, parser.get_rule_names())
    })
}

#[test]
fn perf_simple_expressions() {
    assert_eq!(parse("a;"), "(stat (expr a) ;)");
}

#[test]
fn perf_between_chain() {
    let mut input = String::new();
    for _ in 0..14 {
        input.push_str("between X1 and X2 or between X3 and X4 and\n");
    }
    input.push_str("between X1 and X2 or between X3 and X4;");
    let tree = parse(&input);
    assert!(tree.starts_with("(stat (expr "));
    assert!(tree.ends_with(";)"));
}

#[test]
fn perf_precedence_snapshots() {
    assert_eq!(
        parse("a and b or c;"),
        "(stat (expr (expr (expr a) and (expr b)) or (expr c)) ;)"
    );
    assert_eq!(
        parse("not a ? b : c;"),
        "(stat (expr (expr not (expr a)) ? (expr b) : (expr c)) ;)"
    );
    assert_eq!(parse("(a) b;"), "(stat (expr ( a ) (expr b)) ;)");
    assert_eq!(
        parse("between a and b and not c;"),
        "(stat (expr between (expr (expr a) and (expr b)) and (expr not (expr c))) ;)"
    );
}
