[package]
categories = [
  "development-tools::build-utils",
  "parser-implementations",
  "parsing",
]
description = "ANTLR v4 grammar compiler and Rust source generator"
documentation = "https://docs.rs/dbt-antlr"
edition.workspace = true
homepage.workspace = true
include = ["/Cargo.toml", "/README.md", "/src/**", "/templates/**"]
keywords = ["antlr", "antlr4", "codegen", "lexer", "parser"]
license.workspace = true
name = "dbt-antlr"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "dbt_antlr"
path = "src/lib.rs"

[[bin]]
name = "dbt-antlr"
path = "src/bin/dbt-antlr.rs"

[features]
atn-export = []

[dependencies]
dbt-antlr-g4-parser.workspace = true
dbt-antlr-runtime.workspace = true
icu_casemap = "2.2.0"
icu_properties.workspace = true
intl = { version = "0.6.0", default-features = false, features = [
  "full",
  "normalization",
] }
miette = { version = "7.6.0", default-features = false, features = ["fancy"] }
minijinja.workspace = true
petgraph = { version = "0.8.3", default-features = false, features = ["std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror.workspace = true

[dev-dependencies]
dbt-antlr = { path = ".", features = ["atn-export"] }
dbt-antlr-runtime = { workspace = true, features = ["atn-dump"] }
hmac-sha256 = "1"
insta.workspace = true
memchr.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
