// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Bo Lin
//! End-to-end check of the build-script generation model: parse with the
//! recognizer generated by this crate's `build.rs`.

use build_generate::exprlexer::ExprLexer;
use build_generate::exprparser::ExprParser;
use dbt_antlr_runtime::common_token_stream::CommonTokenStream;
use dbt_antlr_runtime::parser_rule_context::ParserRuleContext;
use dbt_antlr_runtime::recognizer::Recognizer;
use dbt_antlr_runtime::token_factory::CommonTokenFactory;
use dbt_antlr_runtime::{Arena, InputStream};

fn parse_tree(input: &str) -> String {
    Arena::with(|arena| {
        let lexer = ExprLexer::<_, CommonTokenFactory>::new(arena, InputStream::new(input));
        let mut parser = ExprParser::new(arena, CommonTokenStream::new(lexer));
        let tree = parser.prog().expect("parses");
        tree.to_string_tree(parser.get_rule_names())
    })
}

#[test]
fn parses_with_precedence() {
    assert_eq!(
        parse_tree("1+2*3"),
        "(prog (expr (expr 1) + (expr (expr 2) * (expr 3))) <EOF>)"
    );
}

#[test]
fn parses_parentheses() {
    assert_eq!(
        parse_tree("(1+2)*3"),
        "(prog (expr (expr ( (expr (expr 1) + (expr 2)) )) * (expr 3)) <EOF>)"
    );
}
